### ISSUE TITLE
Github monitor可以再上升一点

### ISSUE THREAD

**Issue by hiw0rld** [bloodzer0/ossa#3]
不仅仅是github，还包括
1，网盘
2，pastebin
3，暗网
4，舆论（这个比较难）

**Comment by bloodzer0** [comment]
会的，本来这块都会继续扩展！舆论这个很多时候与公关配合，小公司可能做不到！

**Comment by bloodzer0** [comment]
> 不仅仅是github，还包括
> 1，网盘
> 2，pastebin
> 3，暗网
> 4，舆论（这个比较难）


会的，本来这块都会继续扩展！舆论这个很多时候与公关配合，小公司可能做不到！
--
