### ISSUE TITLE
安全测试文章配图错误

### ISSUE THREAD

**Issue by ttttmr** [bloodzer0/ossa#5]
文章地址 https://bloodzer0.github.io/ossa/application-security/security-testing/#_4

主动型和被动型的配图重了😂

![image](https://user-images.githubusercontent.com/32825326/53220274-a4da1880-369e-11e9-82ff-50b8d7edcf01.png)

**Comment by bloodzer0** [comment]
谢谢你的意见，已修复！

**Comment by bloodzer0** [comment]
> 文章地址 https://bloodzer0.github.io/ossa/application-security/security-testing/#_4
> 
> 主动型和被动型的配图重了😂
> 
> ![image](https://user-images.githubusercontent.com/32825326/53220274-a4da1880-369e-11e9-82ff-50b8d7edcf01.png)

谢谢，已修复
