### ISSUE TITLE
kibana中agent的last keep alive 时间是正确的吗？

### ISSUE THREAD

**Issue by lx277856602** [bloodzer0/ossa#6]
![](https://bloodzer0.oss-cn-beijing.aliyuncs.com/ids_ips/wazuh_kibana_app_4.png)
如题，last keep alive 时间默认安装后相差几个小时，如何解决这个问题呢？

**Comment by bloodzer0** [comment]
kibana的setting->advance中，将dateFormat:tz设置UTC时区
